apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer
  labels:
    app: customer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
      - name: customer
        image: haikalhabibillah/customer:1.0.0
        ports:
        - containerPort: 8084
        env:
        - name: spring.application.name
          value: "customer"
        - name: eureka.client.service-url.defaultZone
          value: "http://eurekaserver:8761/eureka/"
        - name: spring.datasource.url
          value: "jdbc:h2:mem:customerdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"
        - name: spring.datasource.username
          value: "sa"
        - name: spring.datasource.password
          value: ""


