apiVersion: v1
kind: ConfigMap
metadata:
 name: prometheus-config
 labels:
   app: prometheus
data:
 prometheus.yml: |
   global:
     scrape_interval: 15s
   scrape_configs:
     - job_name: 'api-gateway'
       static_configs:
         - targets: ['apigateway:8080']


     - job_name: 'product-service'
       static_configs:
         - targets: ['restapi:8081']


     - job_name: 'order-service'
       static_configs:
         - targets: ['order:8083']


     - job_name: 'payment-service'
       static_configs:
         - targets: ['payment:8082']


     - job_name: 'customer-service'
       static_configs:
         - targets: ['customer:8084']


     - job_name: 'node'
       static_configs:
         - targets: ['node-exporter:9100']
